### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by RealYama** [unbyte/mooc-assistant#2]
![123](https://user-images.githubusercontent.com/55695639/76163065-040dac80-617e-11ea-99c1-333a6462990b.png)
chrome和firefox中
鼠标移到”习题答案“和”视频播放“上不会出现下拉菜单，鼠标也不会变成手指的样子，不会是我操作(智商)有问题吧

**Comment by Delta-in-hub** [comment]
一样的问题

**Comment by unbyte** [comment]
谢谢反馈，十分抱歉，这两周在忙一个项目的交互，没太关注github这边的issue
能否提供复现环境，例如浏览器版本
或是提供console（如果有）的输出

**Comment by RealYama** [comment]
很抱歉没能及时看到回复
Chrome/80.0.3987.116
Firefox/74.0
下图第一张为firefox，二三张为chrome console信息
![_E~A4 $(5M@VV%MDV2$ XM9](https://user-images.githubusercontent.com/55695639/77330096-d027af00-6d59-11ea-864a-30964b818eee.png)
![ch1](https://user-images.githubusercontent.com/55695639/77330114-d61d9000-6d59-11ea-889f-e16023e9c90e.png)
![ch2](https://user-images.githubusercontent.com/55695639/77330124-da49ad80-6d59-11ea-9485-3c28c5d14373.png)
不知道这些是否对你有帮助，如果需要的话愿意提供其他信息

**Comment by unbyte** [comment]
看了一下，出错代码是优学堂用来支持多语言版本切换的，请尝试清空Cookie。在简体中文时不会报错。 @yqw1212

**Comment by RealYama** [comment]
OK! Thanks for your patience and solving this issue.
