### ISSUE TITLE
建议增加下载视频功能

### ISSUE THREAD

**Issue by xmhwws** [unbyte/mooc-assistant#5]
想下载视频到本地观看，希望能增加这个功能

**Comment by unbyte** [comment]
非常不好意思，刚看到issue，会尽快更新视频下载功能

**Comment by unbyte** [comment]
@xmhwws 最后的视频合并不便在前端完成，同时因为视频片段过多直接用浏览器下载会减慢速度，目前网上已经有较为成熟的工具，因此这个功能暂且先搁置。

**Comment by xmhwws** [comment]
OK
