### ISSUE TITLE
一键互评被ban掉了

### ISSUE THREAD

**Issue by tzway** [unbyte/mooc-assistant#6]
如题，今天上午到中午网易一直在显示系统繁忙(估计是在维护)，下午使用的时候就被ban掉了。
填充功能正常。无法正常跳转，原来的click事件失效。

**Comment by unbyte** [comment]
马上修复

**Comment by rubbish-and-world** [comment]
作者太强了（貌似网易用了preventDefault()阻止了click）

**Comment by unbyte** [comment]
~~不考虑firefox的话，问题很好解决~~
~~但是为了兼容firefox我需要找另一种方案~~

https://stackoverflow.com/questions/11456705/are-events-generated-by-firefox-extension-trusted

**Comment by rubbish-and-world** [comment]
> The isTrusted read-only property of the Event interface is a Boolean that is true when the event was generated by a user action, and false when the event was created or modified by a script or jidispatched via EventTarget.dispatchEvent().

这种方式相当于直接把脚本禁了，大佬是如何bypass的呢？:open_mouth:

**Comment by unbyte** [comment]
刚刚试了一下同时也把`chrome.debugger`禁了，现在唯一思路就是在被拦截前先拦截`addEventListener`

**Comment by tzway** [comment]
[Javascript-Anti-Anti-debugger-Code-Protection](https://ohmycoding.com/201903/Javascript-Anti-Anti-debugger-Code-Protection/)

**Comment by unbyte** [comment]
> [Javascript-Anti-Anti-debugger-Code-Protection](https://ohmycoding.com/201903/Javascript-Anti-Anti-debugger-Code-Protection/)

这个和慕课的anti debugger不是同一种东西

**Comment by unbyte** [comment]
目前线索:
1. 拦截js是动态插入的
2. 我在document_start时注入插件脚本，此时拦截js已经被插入
3. chrome.debugger被禁用
4. 判断方式是只读属性isTrusted，除了chrome.debugger似乎没有能修改的方法

**Comment by unbyte** [comment]
可以互评了，视频如下

[ok.zip](https://github.com/unbyte/mooc-assistant/files/4657247/ok.zip)

**Comment by unbyte** [comment]
XD哭笑不得，慕课又更新了把反脚本给更没了，可能他们也还在调试

**Comment by tzway** [comment]
> 
> 
> XD哭笑不得，慕课又更新了把反脚本给更没了，可能他们也还在调试

难道是可以乘机fuckitnow吗

**Comment by rubbish-and-world** [comment]
~~射射大佬，已经谢了~~
太强了:clap::clap::clap:

**Comment by unbyte** [comment]
感觉一觉睡醒慕课会又ban了，我尽快找到解决方案吧
这条issue先开着

**Comment by unbyte** [comment]
> 目前线索:
> 
> 1. 拦截js是动态插入的
> 2. 我在document_start时注入插件脚本，此时拦截js已经被插入
> 3. chrome.debugger被禁用
> 4. 判断方式是只读属性isTrusted，除了chrome.debugger似乎没有能修改的方法

这里测试的时候出现了问题，但是思路是对的。

已经发现了疑似解决方法，缺少一个能测试互评的账号 @karsacui @rubbish-and-world 😂有无可以互评的号方便测试一下的

**Comment by tzway** [comment]
> 
> 
> > 目前线索:
> > 
> > 1. 拦截js是动态插入的
> > 2. 我在document_start时注入插件脚本，此时拦截js已经被插入
> > 3. chrome.debugger被禁用
> > 4. 判断方式是只读属性isTrusted，除了chrome.debugger似乎没有能修改的方法
> 
> 这里测试的时候出现了问题，但是思路是对的。
> 
> 已经发现了疑似解决方法，缺少一个能测试互评的账号 @karsacui @rubbish-and-world 😂有无可以互评的号方便测试一下的

发到邮箱了

**Comment by unbyte** [comment]
> > > 目前线索:
> > > 
> > > 1. 拦截js是动态插入的
> > > 2. 我在document_start时注入插件脚本，此时拦截js已经被插入
> > > 3. chrome.debugger被禁用
> > > 4. 判断方式是只读属性isTrusted，除了chrome.debugger似乎没有能修改的方法
> > 
> > 
> > 这里测试的时候出现了问题，但是思路是对的。
> > 已经发现了疑似解决方法，缺少一个能测试互评的账号 @karsacui @rubbish-and-world 😂有无可以互评的号方便测试一下的
> 
> 发到邮箱了

等不及了，所以手动模拟了一下，应该问题不大，就直接发release了

这个issue先不关，等验证确实可以互评之后关掉
