### ISSUE TITLE
老哥，最近这个互评不能一键到底了

### ISSUE THREAD

**Issue by Lizidong01** [unbyte/mooc-assistant#8]
互评完了他不会跳转下一个互评位置了，而且貌似现在插件也不能自动评价了

**Comment by unbyte** [comment]
已经更新了，等待商店推送新版本 v2.2.1
老哥更新之后帮忙测试一下是不是可以正常用了然后回一下issue，我现在没有可以互评的账号

**Comment by unbyte** [comment]
看了一下，chrome和firefox商店新版本都已经审核完毕了，可以在浏览器插件管理页面点更新

**Comment by Lizidong01** [comment]
ok，我看看

**Comment by Lizidong01** [comment]
现在可以用了，，一键三十份刚刚成功了。莫得问题。

**Comment by unbyte** [comment]
> 现在可以用了，，一键三十份刚刚成功了。莫得问题。

ok，多谢
